### ISSUE TITLE
D2 - Unable to select Instant/Pad FX slots 

### ISSUE THREAD

**Issue by kartguru** [Phando/SupremeEditionEdits#1]
Just reporting a bug on the D2. Cheers for the extension to an already very cool Mod.

Traktor 3.5.2
D2 Controller
Supreme Edition 3.0 BETA 31.1 Release Candidate 2
SupremeEditionEdits-0.2.0

On my D2, overwriting the 31.1 files with your 0.2.0 release removes the ability to select Instant/Pad FX slots using SHIFT when in Instant/Pad FX mode. I returned to the default 31.1 RC2 qml files and this returned the expected behaviour.

**Comment by Phando** [comment]
Thanks for using the mod and for the feedback. Can’t you let me know the expected default behavior, I’ll look into it.

**Comment by kartguru** [comment]
No problems, and thanks for looking into it. I expect the behaviour on your S5 would be similar to the D2 but maybe as you've acknowledge the duplicate effects in the 2nd slot (i kinda feel 'bank' is a better term) you are not experiencing the same.

In 31.1, by clicking on SHIFT when in Instant/Pad FX mode you are presented with two illuminated (white) pads. Here you can switch between the Instant/Pad FX slots/banks. Going by the documentation, 4 slots/banks (of 2 rows) holding up to 64 effects.

The original and your edit have almost duplicate effects by default.  PadFX 1.1 vs PadFX 2.1 however has a different colour LED specified on each slot as well as some very subtle name differences. See InstantFXs.qml. You'll find in the original when you switch between these two slots/banks (using SHIFT) the first pad (starting as PadFX 1.1) will change from purple to red when defined as PadFX 2.1.

Hope that makes sense. 

Cheers

**Comment by Phando** [comment]
@kartguru with the release of Beta 32, it looks like my effects strategy has been rolled into the main mod. If this bug persists in the new system, we will fix it over there. I think this repo might have served it purpose.

**Comment by kartguru** [comment]
I meant to update this as well when I saw the release. It looks like its been ironed out.

Congrats on getting your idea built into the main build.
